<?php
if ( ! defined( 'ABSPATH' ) ) exit;
/** * Template Name: Custom Template
 * Page Template
 *
 * This template is the default page template. It is used to display content when someone is viewing a
 * singular view of a page ('page' post_type) unless another page template overrules this one.
 * @link http://codex.wordpress.org/Pages
 *
 * @package WooFramework
 * @subpackage Template
 */
get_header();	global $woo_options;?>    <div id="content" class="page col-full">		        <div class="section-wrapper">		    	<?php woo_main_before(); ?>		<section id="main" class="col-right">        <?php        	if ( have_posts() ) { $count = 0;        		while ( have_posts() ) { the_post(); $count++;        ?>            <article <?php post_class(); ?>>                <section class="entry">									                	<?php the_content(); ?>					<?php wp_link_pages( array( 'before' => '<div class="page-link">' . __( 'Pages:', 'woothemes' ), 'after' => '</div>' ) ); ?>															<!--div class="blog" id="blog">						<h2>Recent Posts</h2>						<div class="recent-posts">							<?php $the_query = new WP_Query( 'posts_per_page=5' ); ?>							<?php while ($the_query -> have_posts()) : $the_query -> the_post(); ?>							<ul class="post-detail">							<li class="post-image"><?php woo_image( 'width=400&height=225&class=thumbnail' ); ?></li>							<li class="post-date"><?php the_time( get_option( 'date_format' ) ); ?></li>							<li class="post-title"><a href="<?php the_permalink() ?>"><?php the_title(); ?></a></li>							<li class="separator"></li>							<li class="post-details"><?php the_excerpt(__('(more…)')); ?></li>							<li class=""><a class="read-more" href="<?php the_permalink() ?>">Read more</a></li>							</ul>							<?php 							endwhile;							wp_reset_postdata();							?>													</div>					</div-->				</section><!-- /.entry -->								<?php edit_post_link( __( '{ Edit }', 'woothemes' ), '<span class="small">', '</span>' ); ?>            </article><!-- /.post -->            <?php            	// Determine wether or not to display comments here, based on "Theme Options".            	if ( isset( $woo_options['woo_comments'] ) && in_array( $woo_options['woo_comments'], array( 'page', 'both' ) ) ) {            		comments_template();            	}				} // End WHILE Loop			} else {		?>			<article <?php post_class(); ?>>            	<p><?php _e( 'Sorry, no posts matched your criteria.', 'woothemes' ); ?></p>            </article><!-- /.post -->        <?php } // End IF Statement ?>						</section><!-- /#main -->		<?php woo_main_after(); ?>        <?php get_sidebar(); ?>				        </div><!-- /.section-wrapper -->		    </div><!-- /#content --><?php get_footer(); ?>